/*
 * EventSwipeView.java
 */
package eventswipe;

import eventswipe.EventSwipeData.BookingList;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.JPanel;
import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.Timer;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;

/**
 * The application's main frame.
 */
public class EventSwipeView extends FrameView {

    public EventSwipeView(SingleFrameApplication app) {
        super(app);
        ResourceMap resourceMap = Application.getInstance(eventswipe.EventSwipeApp.class)
                                  .getContext().getResourceMap(EventSwipeView.class);
        titleInputDefault = resourceMap.getString("eventTitleInputDefault");
        fileInputDefault = resourceMap.getString("fileInputDefault");
        idInputDefault = resourceMap.getString("idInputDefault");
        initComponents();
        updateBookingPanel(false);
        try {
            Image i = ImageIO.read(getClass().getResource("/eventswipe/resources/logo.jpeg"));
            this.getFrame().setIconImage(i);
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
        this.getFrame().setPreferredSize(new Dimension(750, 410));
        this.getFrame().setResizable(false);
        
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = EventSwipeApp.getApplication().getMainFrame();
            aboutBox = new EventSwipeAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        EventSwipeApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        clearButton1 = new javax.swing.JButton();
        studentNumberInput = new javax.swing.JFormattedTextField();
        enterStudentNumberButton = new javax.swing.JButton();
        bookingStatusScrollPane = new javax.swing.JScrollPane();
        bookingStatusTextArea = new javax.swing.JTextArea();
        backButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        studentNumberInputLabel = new javax.swing.JLabel();
        statusDisplayTextField = new javax.swing.JFormattedTextField();
        entrySlotDisplayTextField = new javax.swing.JFormattedTextField();
        attendeeCountDisplayTextField = new javax.swing.JFormattedTextField();
        attendeeCountLabel = new javax.swing.JLabel();
        entrySlotLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        checkingModeToggle = new javax.swing.JToggleButton();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        toggleMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        configPanel = new javax.swing.JPanel();
        eventTitleInputLabel = new javax.swing.JLabel();
        yesBookingRadioButton = new javax.swing.JRadioButton();
        noBookingRadioButton = new javax.swing.JRadioButton();
        requireBookingLabel = new javax.swing.JLabel();
        okConfigButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        bookingDetailsPanel = new javax.swing.JPanel();
        entrySlotBookingListLabel1 = new javax.swing.JLabel();
        entrySlotsLabel = new javax.swing.JLabel();
        bookingListBrowseButton1 = new javax.swing.JButton();
        entrySlotsSpinner = new javax.swing.JSpinner(new javax.swing.SpinnerNumberModel(1, 1, EventSwipeData.MAX_ENTRY_SLOTS, 1));
        entrySlotBookingListFilePathInput3 = new javax.swing.JFormattedTextField();
        entrySlotBookingListFilePathInput2 = new javax.swing.JFormattedTextField();
        entrySlotBookingListLabel3 = new javax.swing.JLabel();
        entrySlotBookingListLabel2 = new javax.swing.JLabel();
        waitingListFilePathInput = new javax.swing.JFormattedTextField();
        waitingListFileLabel = new javax.swing.JLabel();
        bookingListBrowseButton2 = new javax.swing.JButton();
        bookingListBrowseButton3 = new javax.swing.JButton();
        waitingListBrowseButton = new javax.swing.JButton();
        noWaitingListRadioButton = new javax.swing.JRadioButton();
        waitingListLabel = new javax.swing.JLabel();
        entrySlotBookingListFilePathInput1 = new javax.swing.JFormattedTextField();
        yesWaitingListRadioButton = new javax.swing.JRadioButton();
        eventTitleInput = new javax.swing.JFormattedTextField();
        clearButton = new javax.swing.JButton();
        requireBookingButtonGroup = new javax.swing.ButtonGroup();
        waitingListButtonGroup = new javax.swing.ButtonGroup();
        preConfigPanel = new javax.swing.JPanel();
        titleLoginPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        logInLabel = new javax.swing.JLabel();
        useOfflineLabel = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        startOfflineButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        useOfflineDescription = new javax.swing.JTextArea();
        passwordLabel = new javax.swing.JLabel();
        logInButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        loginOfflineSeparator = new javax.swing.JSeparator();
        titlePanel = new javax.swing.JPanel();
        smallLogoLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        mainTitle = new javax.swing.JLabel();
        onlineConfigPanel = new javax.swing.JPanel();
        okConfigButton1 = new javax.swing.JButton();
        bookingDetailsPanel1 = new javax.swing.JPanel();
        entrySlotIdLabel1 = new javax.swing.JLabel();
        entrySlotsLabel1 = new javax.swing.JLabel();
        entrySlotsSpinner1 = new javax.swing.JSpinner(new javax.swing.SpinnerNumberModel(1, 1, EventSwipeData.MAX_ENTRY_SLOTS, 1));
        entrySlotIdInput3 = new javax.swing.JFormattedTextField();
        entrySlotIdInput2 = new javax.swing.JFormattedTextField();
        entrySlotIdLabel3 = new javax.swing.JLabel();
        entrySlotIdLabel2 = new javax.swing.JLabel();
        noLoadWaitingListRadioButton = new javax.swing.JRadioButton();
        loadWaitingListLabel = new javax.swing.JLabel();
        entrySlotIdInput1 = new javax.swing.JFormattedTextField();
        yesLoadWaitingListRadioButton = new javax.swing.JRadioButton();
        generatedTitle1 = new javax.swing.JTextField();
        generatedTitle2 = new javax.swing.JTextField();
        generatedTitle3 = new javax.swing.JTextField();
        loadEventButton1 = new javax.swing.JButton();
        loadEventButton2 = new javax.swing.JButton();
        loadEventButton3 = new javax.swing.JButton();
        generatedTitleLabel1 = new javax.swing.JLabel();
        generatedTitleLabel2 = new javax.swing.JLabel();
        generatedTitleLabel3 = new javax.swing.JLabel();
        aboutEventLabel = new javax.swing.JLabel();
        clearButton2 = new javax.swing.JButton();

        mainPanel.setMinimumSize(new java.awt.Dimension(720, 350));
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(720, 350));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(eventswipe.EventSwipeApp.class).getContext().getResourceMap(EventSwipeView.class);
        clearButton1.setText(resourceMap.getString("clearButton1.text")); // NOI18N
        clearButton1.setFocusPainted(false);
        clearButton1.setFocusable(false);
        clearButton1.setName("clearButton1"); // NOI18N
        clearButton1.setRequestFocusEnabled(false);
        clearButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton1ActionPerformed(evt);
            }
        });

        studentNumberInput.setName("studentNumberInput"); // NOI18N
        javax.swing.Action save = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                EventSwipeApp.getApplication().saveAttendeesToFile();
            }
        };
        javax.swing.Action toggleBooking = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                checkingModeToggle.doClick();
            }
        };
        javax.swing.Action checkBooking = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                checkBooking();
            }
        };
        studentNumberInput.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_S,
            java.awt.event.InputEvent.CTRL_DOWN_MASK),
        "save");
    studentNumberInput.getActionMap().put("save", save);
    studentNumberInput.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_T,
        java.awt.event.InputEvent.CTRL_DOWN_MASK),
    "toggleBooking");
    studentNumberInput.getActionMap().put("toggleBooking", toggleBooking);
    studentNumberInput.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0),
        "enterStudentNumber");
    studentNumberInput.getActionMap().put("enterStudentNumber",
        checkBooking);

    enterStudentNumberButton.setText(resourceMap.getString("enterStudentNumberButton.text")); // NOI18N
    enterStudentNumberButton.setFocusable(false);
    enterStudentNumberButton.setName("enterStudentNumberButton"); // NOI18N
    enterStudentNumberButton.setRequestFocusEnabled(false);
    enterStudentNumberButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            enterStudentNumberButtonActionPerformed(evt);
        }
    });

    bookingStatusScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
    bookingStatusScrollPane.setName("bookingStatusScrollPane"); // NOI18N

    bookingStatusTextArea.setColumns(20);
    bookingStatusTextArea.setEditable(false);
    bookingStatusTextArea.setRows(5);
    bookingStatusTextArea.setFocusable(false);
    bookingStatusTextArea.setName("bookingStatusTextArea"); // NOI18N
    bookingStatusTextArea.setRequestFocusEnabled(false);
    bookingStatusScrollPane.setViewportView(bookingStatusTextArea);

    backButton.setText(resourceMap.getString("backButton.text")); // NOI18N
    backButton.setFocusable(false);
    backButton.setName("backButton"); // NOI18N
    backButton.setRequestFocusEnabled(false);
    backButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            backButtonActionPerformed(evt);
        }
    });

    saveButton.setText(resourceMap.getString("saveButton.text")); // NOI18N
    saveButton.setFocusable(false);
    saveButton.setName("saveButton"); // NOI18N
    saveButton.setRequestFocusEnabled(false);
    saveButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            saveButtonActionPerformed(evt);
        }
    });

    studentNumberInputLabel.setText(resourceMap.getString("studentNumberInputLabel.text")); // NOI18N
    studentNumberInputLabel.setName("studentNumberInputLabel"); // NOI18N

    statusDisplayTextField.setEditable(false);
    statusDisplayTextField.setText(resourceMap.getString("statusDisplayTextField.text")); // NOI18N
    statusDisplayTextField.setFocusable(false);
    statusDisplayTextField.setFont(resourceMap.getFont("statusDisplayTextField.font")); // NOI18N
    statusDisplayTextField.setName("statusDisplayTextField"); // NOI18N

    entrySlotDisplayTextField.setEditable(false);
    entrySlotDisplayTextField.setText(resourceMap.getString("entrySlotDisplayTextField.text")); // NOI18N
    entrySlotDisplayTextField.setFocusable(false);
    entrySlotDisplayTextField.setFont(resourceMap.getFont("entrySlotDisplayTextField.font")); // NOI18N
    entrySlotDisplayTextField.setName("entrySlotDisplayTextField"); // NOI18N
    entrySlotDisplayTextField.setRequestFocusEnabled(false);

    attendeeCountDisplayTextField.setEditable(false);
    attendeeCountDisplayTextField.setText(resourceMap.getString("attendeeCountDisplayTextField.text")); // NOI18N
    attendeeCountDisplayTextField.setFocusable(false);
    attendeeCountDisplayTextField.setFont(resourceMap.getFont("attendeeCountDisplayTextField.font")); // NOI18N
    attendeeCountDisplayTextField.setName("attendeeCountDisplayTextField"); // NOI18N
    attendeeCountDisplayTextField.setRequestFocusEnabled(false);

    attendeeCountLabel.setText(resourceMap.getString("attendeeCountLabel.text")); // NOI18N
    attendeeCountLabel.setName("attendeeCountLabel"); // NOI18N

    entrySlotLabel.setText(resourceMap.getString("entrySlotLabel.text")); // NOI18N
    entrySlotLabel.setName("entrySlotLabel"); // NOI18N

    statusLabel.setText(resourceMap.getString("statusLabel.text")); // NOI18N
    statusLabel.setName("statusLabel"); // NOI18N

    javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(eventswipe.EventSwipeApp.class).getContext().getActionMap(EventSwipeView.class, this);
    checkingModeToggle.setAction(actionMap.get("checkingModeToggleClick")); // NOI18N
    checkingModeToggle.setText(resourceMap.getString("checkingModeToggle.text")); // NOI18N
    checkingModeToggle.setToolTipText(resourceMap.getString("checkingModeToggle.toolTipText")); // NOI18N
    checkingModeToggle.setFocusPainted(false);
    checkingModeToggle.setFocusable(false);
    checkingModeToggle.setName("checkingModeToggle"); // NOI18N
    checkingModeToggle.setRequestFocusEnabled(false);
    checkingModeToggle.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            checkingModeToggleActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
    mainPanel.setLayout(mainPanelLayout);
    mainPanelLayout.setHorizontalGroup(
        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bookingStatusScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                            .addComponent(studentNumberInputLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(studentNumberInput)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(enterStudentNumberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                            .addComponent(statusLabel)
                            .addGap(10, 10, 10)
                            .addComponent(statusDisplayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(entrySlotLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(entrySlotDisplayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(attendeeCountLabel)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(checkingModeToggle, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addComponent(attendeeCountDisplayTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(211, 211, 211)
                    .addComponent(clearButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );
    mainPanelLayout.setVerticalGroup(
        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(mainPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(studentNumberInputLabel)
                .addComponent(studentNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(enterStudentNumberButton)
                .addComponent(checkingModeToggle))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(statusDisplayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(attendeeCountDisplayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(entrySlotDisplayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(statusLabel)
                .addComponent(entrySlotLabel)
                .addComponent(attendeeCountLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(bookingStatusScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(backButton)
                .addComponent(clearButton1)
                .addComponent(saveButton))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    menuBar.setName("menuBar"); // NOI18N

    fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
    fileMenu.setName("fileMenu"); // NOI18N

    toggleMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
    toggleMenuItem.setText(resourceMap.getString("toggleMenuItem.text")); // NOI18N
    toggleMenuItem.setEnabled(false);
    toggleMenuItem.setName("toggleMenuItem"); // NOI18N
    toggleMenuItem.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            toggleMenuItemActionPerformed(evt);
        }
    });
    fileMenu.add(toggleMenuItem);

    saveMenuItem.setAction(actionMap.get("saveAttendeesToFile")); // NOI18N
    saveMenuItem.setText(resourceMap.getString("saveMenuItem.text")); // NOI18N
    saveMenuItem.setName("saveMenuItem"); // NOI18N
    fileMenu.add(saveMenuItem);

    exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
    exitMenuItem.setName("exitMenuItem"); // NOI18N
    fileMenu.add(exitMenuItem);

    menuBar.add(fileMenu);

    helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
    helpMenu.setName("helpMenu"); // NOI18N

    aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
    aboutMenuItem.setName("aboutMenuItem"); // NOI18N
    helpMenu.add(aboutMenuItem);

    menuBar.add(helpMenu);

    configPanel.setMinimumSize(new java.awt.Dimension(720, 350));
    configPanel.setName("configPanel"); // NOI18N
    configPanel.setPreferredSize(new java.awt.Dimension(720, 350));

    eventTitleInputLabel.setText(resourceMap.getString("eventTitleInputLabel.text")); // NOI18N
    eventTitleInputLabel.setName("eventTitleInputLabel"); // NOI18N

    requireBookingButtonGroup.add(yesBookingRadioButton);
    yesBookingRadioButton.setText(resourceMap.getString("yesBookingRadioButton.text")); // NOI18N
    yesBookingRadioButton.setName("yesBookingRadioButton"); // NOI18N
    yesBookingRadioButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            yesBookingRadioButtonActionPerformed(evt);
        }
    });

    requireBookingButtonGroup.add(noBookingRadioButton);
    noBookingRadioButton.setText(resourceMap.getString("noBookingRadioButton.text")); // NOI18N
    noBookingRadioButton.setName("noBookingRadioButton"); // NOI18N
    noBookingRadioButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            noBookingRadioButtonActionPerformed(evt);
        }
    });

    requireBookingLabel.setText(resourceMap.getString("requireBookingLabel.text")); // NOI18N
    requireBookingLabel.setName("requireBookingLabel"); // NOI18N

    okConfigButton.setText(resourceMap.getString("okConfigButton.text")); // NOI18N
    okConfigButton.setName("okConfigButton"); // NOI18N
    okConfigButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            okConfigButtonActionPerformed(evt);
        }
    });

    titleLabel.setFont(resourceMap.getFont("titleLabel.font")); // NOI18N
    titleLabel.setText(resourceMap.getString("titleLabel.text")); // NOI18N
    titleLabel.setName("titleLabel"); // NOI18N

    bookingDetailsPanel.setEnabled(false);
    bookingDetailsPanel.setName("bookingDetailsPanel"); // NOI18N

    entrySlotBookingListLabel1.setText(resourceMap.getString("entrySlotBookingListLabel1.text")); // NOI18N
    entrySlotBookingListLabel1.setName("entrySlotBookingListLabel1"); // NOI18N

    entrySlotsLabel.setText(resourceMap.getString("entrySlotsLabel.text")); // NOI18N
    entrySlotsLabel.setName("entrySlotsLabel"); // NOI18N

    bookingListBrowseButton1.setText(resourceMap.getString("bookingListBrowseButton1.text")); // NOI18N
    bookingListBrowseButton1.setName("bookingListBrowseButton1"); // NOI18N
    bookingListBrowseButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            browseFileAction(evt);
        }
    });

    entrySlotsSpinner.setName("entrySlotsSpinner"); // NOI18N
    entrySlotsSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            entrySlotsSpinnerStateChanged(evt);
        }
    });

    entrySlotBookingListFilePathInput3.setText(fileInputDefault);
    entrySlotBookingListFilePathInput3.setName("entrySlotBookingListFilePathInput3"); // NOI18N
    entrySlotBookingListFilePathInput3.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            inputFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            inputFocusLost(evt);
        }
    });

    entrySlotBookingListFilePathInput2.setText(fileInputDefault);
    entrySlotBookingListFilePathInput2.setName("entrySlotBookingListFilePathInput2"); // NOI18N
    entrySlotBookingListFilePathInput2.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            inputFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            inputFocusLost(evt);
        }
    });

    entrySlotBookingListLabel3.setText(resourceMap.getString("entrySlotBookingListLabel3.text")); // NOI18N
    entrySlotBookingListLabel3.setName("entrySlotBookingListLabel3"); // NOI18N

    entrySlotBookingListLabel2.setText(resourceMap.getString("entrySlotBookingListLabel2.text")); // NOI18N
    entrySlotBookingListLabel2.setName("entrySlotBookingListLabel2"); // NOI18N

    waitingListFilePathInput.setText(fileInputDefault);
    waitingListFilePathInput.setName("waitingListFilePathInput"); // NOI18N
    waitingListFilePathInput.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            inputFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            inputFocusLost(evt);
        }
    });

    waitingListFileLabel.setText(resourceMap.getString("waitingListFileLabel.text")); // NOI18N
    waitingListFileLabel.setName("waitingListFileLabel"); // NOI18N

    bookingListBrowseButton2.setText(resourceMap.getString("bookingListBrowseButton2.text")); // NOI18N
    bookingListBrowseButton2.setName("bookingListBrowseButton2"); // NOI18N
    bookingListBrowseButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            browseFileAction(evt);
        }
    });

    bookingListBrowseButton3.setText(resourceMap.getString("bookingListBrowseButton3.text")); // NOI18N
    bookingListBrowseButton3.setName("bookingListBrowseButton3"); // NOI18N
    bookingListBrowseButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            browseFileAction(evt);
        }
    });

    waitingListBrowseButton.setText(resourceMap.getString("waitingListBrowseButton.text")); // NOI18N
    waitingListBrowseButton.setName("waitingListBrowseButton"); // NOI18N
    waitingListBrowseButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            browseFileAction(evt);
        }
    });

    waitingListButtonGroup.add(noWaitingListRadioButton);
    noWaitingListRadioButton.setText(resourceMap.getString("noWaitingListRadioButton.text")); // NOI18N
    noWaitingListRadioButton.setName("noWaitingListRadioButton"); // NOI18N
    noWaitingListRadioButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            noWaitingListRadioButtonActionPerformed(evt);
        }
    });

    waitingListLabel.setText(resourceMap.getString("waitingListLabel.text")); // NOI18N
    waitingListLabel.setName("waitingListLabel"); // NOI18N

    entrySlotBookingListFilePathInput1.setText(fileInputDefault);
    entrySlotBookingListFilePathInput1.setName("entrySlotBookingListFilePathInput1"); // NOI18N
    entrySlotBookingListFilePathInput1.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            inputFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            inputFocusLost(evt);
        }
    });

    waitingListButtonGroup.add(yesWaitingListRadioButton);
    yesWaitingListRadioButton.setText(resourceMap.getString("yesWaitingListRadioButton.text")); // NOI18N
    yesWaitingListRadioButton.setName("yesWaitingListRadioButton"); // NOI18N
    yesWaitingListRadioButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            yesWaitingListRadioButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout bookingDetailsPanelLayout = new javax.swing.GroupLayout(bookingDetailsPanel);
    bookingDetailsPanel.setLayout(bookingDetailsPanelLayout);
    bookingDetailsPanelLayout.setHorizontalGroup(
        bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingDetailsPanelLayout.createSequentialGroup()
            .addGroup(bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(bookingDetailsPanelLayout.createSequentialGroup()
                    .addComponent(waitingListLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(yesWaitingListRadioButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(noWaitingListRadioButton)
                    .addGap(160, 160, 160)
                    .addComponent(waitingListFileLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(waitingListFilePathInput, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(waitingListBrowseButton))
                .addGroup(bookingDetailsPanelLayout.createSequentialGroup()
                    .addComponent(entrySlotBookingListLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(entrySlotBookingListFilePathInput3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(bookingListBrowseButton3))
                .addGroup(bookingDetailsPanelLayout.createSequentialGroup()
                    .addComponent(entrySlotBookingListLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(entrySlotBookingListFilePathInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(bookingListBrowseButton2))
                .addGroup(bookingDetailsPanelLayout.createSequentialGroup()
                    .addComponent(entrySlotsLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(entrySlotsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(entrySlotBookingListLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(entrySlotBookingListFilePathInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(bookingListBrowseButton1)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    bookingDetailsPanelLayout.setVerticalGroup(
        bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(bookingDetailsPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(entrySlotBookingListFilePathInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(entrySlotBookingListLabel1)
                .addComponent(bookingListBrowseButton1)
                .addComponent(entrySlotsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(entrySlotsLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(entrySlotBookingListFilePathInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(entrySlotBookingListLabel2)
                .addComponent(bookingListBrowseButton2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(entrySlotBookingListFilePathInput3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(entrySlotBookingListLabel3)
                .addComponent(bookingListBrowseButton3))
            .addGap(26, 26, 26)
            .addGroup(bookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(waitingListBrowseButton)
                .addComponent(waitingListFilePathInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(waitingListFileLabel)
                .addComponent(waitingListLabel)
                .addComponent(yesWaitingListRadioButton)
                .addComponent(noWaitingListRadioButton))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    eventTitleInput.setText(titleInputDefault);
    eventTitleInput.setName("eventTitleInput"); // NOI18N
    eventTitleInput.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            inputFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            inputFocusLost(evt);
        }
    });
    javax.swing.Action checkConfiguration = new AbstractAction() {
        public void actionPerformed(ActionEvent e) {
            checkConfiguration();
        }
    };
    eventTitleInput.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0),
        "checkConfiguration");
    eventTitleInput.getActionMap().put("checkConfiguration", checkConfiguration);

    clearButton.setText(resourceMap.getString("clearButton.text")); // NOI18N
    clearButton.setName("clearButton"); // NOI18N
    clearButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            clearButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout configPanelLayout = new javax.swing.GroupLayout(configPanel);
    configPanel.setLayout(configPanelLayout);
    configPanelLayout.setHorizontalGroup(
        configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(configPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(configPanelLayout.createSequentialGroup()
                    .addComponent(requireBookingLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(yesBookingRadioButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(noBookingRadioButton))
                .addGroup(configPanelLayout.createSequentialGroup()
                    .addComponent(eventTitleInputLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(eventTitleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(titleLabel)
                .addComponent(bookingDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configPanelLayout.createSequentialGroup()
                    .addComponent(okConfigButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 504, Short.MAX_VALUE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );
    configPanelLayout.setVerticalGroup(
        configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(configPanelLayout.createSequentialGroup()
            .addGap(41, 41, 41)
            .addComponent(titleLabel)
            .addGap(18, 18, 18)
            .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(eventTitleInputLabel)
                .addComponent(eventTitleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(requireBookingLabel)
                .addComponent(yesBookingRadioButton)
                .addComponent(noBookingRadioButton))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(bookingDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
            .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(clearButton)
                .addComponent(okConfigButton))
            .addContainerGap())
    );

    preConfigPanel.setMinimumSize(new java.awt.Dimension(720, 350));
    preConfigPanel.setName("preConfigPanel"); // NOI18N

    titleLoginPanel.setName("titleLoginPanel"); // NOI18N

    loginPanel.setName("loginPanel"); // NOI18N

    logInLabel.setFont(resourceMap.getFont("logInLabel.font")); // NOI18N
    logInLabel.setText(resourceMap.getString("logInLabel.text")); // NOI18N
    logInLabel.setName("logInLabel"); // NOI18N

    useOfflineLabel.setFont(resourceMap.getFont("useOfflineLabel.font")); // NOI18N
    useOfflineLabel.setText(resourceMap.getString("useOfflineLabel.text")); // NOI18N
    useOfflineLabel.setName("useOfflineLabel"); // NOI18N

    passwordInput.setText(resourceMap.getString("passwordInput.text")); // NOI18N
    passwordInput.setName("passwordInput"); // NOI18N

    startOfflineButton.setText(resourceMap.getString("startOfflineButton.text")); // NOI18N
    startOfflineButton.setName("startOfflineButton"); // NOI18N

    jScrollPane1.setBorder(null);
    jScrollPane1.setName("jScrollPane1"); // NOI18N

    useOfflineDescription.setBackground(resourceMap.getColor("useOfflineDescription.background")); // NOI18N
    useOfflineDescription.setColumns(20);
    useOfflineDescription.setEditable(false);
    useOfflineDescription.setFont(resourceMap.getFont("useOfflineDescription.font")); // NOI18N
    useOfflineDescription.setLineWrap(true);
    useOfflineDescription.setRows(5);
    useOfflineDescription.setText(resourceMap.getString("useOfflineDescription.text")); // NOI18N
    useOfflineDescription.setWrapStyleWord(true);
    useOfflineDescription.setAutoscrolls(false);
    useOfflineDescription.setBorder(null);
    useOfflineDescription.setName("useOfflineDescription"); // NOI18N
    jScrollPane1.setViewportView(useOfflineDescription);

    passwordLabel.setText(resourceMap.getString("passwordLabel.text")); // NOI18N
    passwordLabel.setName("passwordLabel"); // NOI18N

    logInButton.setAction(actionMap.get("logIn")); // NOI18N
    logInButton.setText(resourceMap.getString("logInButton.text")); // NOI18N
    logInButton.setName("logInButton"); // NOI18N

    usernameLabel.setText(resourceMap.getString("usernameLabel.text")); // NOI18N
    usernameLabel.setName("usernameLabel"); // NOI18N

    usernameInput.setText(resourceMap.getString("usernameInput.text")); // NOI18N
    usernameInput.setName("usernameInput"); // NOI18N

    loginOfflineSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
    loginOfflineSeparator.setName("loginOfflineSeparator"); // NOI18N

    javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
    loginPanel.setLayout(loginPanelLayout);
    loginPanelLayout.setHorizontalGroup(
        loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(loginPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(logInLabel)
                .addComponent(usernameLabel)
                .addComponent(passwordLabel)
                .addComponent(usernameInput)
                .addComponent(passwordInput, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addComponent(logInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addComponent(loginOfflineSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addComponent(useOfflineLabel)
                .addComponent(startOfflineButton, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
            .addGap(23, 23, 23))
    );
    loginPanelLayout.setVerticalGroup(
        loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(loginPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(loginOfflineSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createSequentialGroup()
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loginPanelLayout.createSequentialGroup()
                            .addComponent(logInLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(usernameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(passwordLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(loginPanelLayout.createSequentialGroup()
                            .addComponent(useOfflineLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logInButton)
                        .addComponent(startOfflineButton))))
            .addContainerGap())
    );

    titlePanel.setName("titlePanel"); // NOI18N

    smallLogoLabel.setIcon(resourceMap.getIcon("smallLogoLabel.icon")); // NOI18N
    smallLogoLabel.setText(resourceMap.getString("smallLogoLabel.text")); // NOI18N
    smallLogoLabel.setName("smallLogoLabel"); // NOI18N

    versionLabel.setFont(resourceMap.getFont("versionLabel.font")); // NOI18N
    versionLabel.setText(resourceMap.getString("versionLabel.text")); // NOI18N
    versionLabel.setName("versionLabel"); // NOI18N

    mainTitle.setFont(resourceMap.getFont("mainTitle.font")); // NOI18N
    mainTitle.setText(resourceMap.getString("mainTitle.text")); // NOI18N
    mainTitle.setName("mainTitle"); // NOI18N

    javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
    titlePanel.setLayout(titlePanelLayout);
    titlePanelLayout.setHorizontalGroup(
        titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(titlePanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(smallLogoLabel)
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titlePanelLayout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18))
                .addGroup(titlePanelLayout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(versionLabel)
                    .addContainerGap())))
    );
    titlePanelLayout.setVerticalGroup(
        titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(titlePanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titlePanelLayout.createSequentialGroup()
                    .addComponent(mainTitle)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(versionLabel))
                .addComponent(smallLogoLabel))
            .addGap(14, 14, 14))
    );

    javax.swing.GroupLayout titleLoginPanelLayout = new javax.swing.GroupLayout(titleLoginPanel);
    titleLoginPanel.setLayout(titleLoginPanelLayout);
    titleLoginPanelLayout.setHorizontalGroup(
        titleLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(titleLoginPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(titleLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );
    titleLoginPanelLayout.setVerticalGroup(
        titleLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(titleLoginPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    javax.swing.GroupLayout preConfigPanelLayout = new javax.swing.GroupLayout(preConfigPanel);
    preConfigPanel.setLayout(preConfigPanelLayout);
    preConfigPanelLayout.setHorizontalGroup(
        preConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, preConfigPanelLayout.createSequentialGroup()
            .addContainerGap(24, Short.MAX_VALUE)
            .addComponent(titleLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(19, 19, 19))
    );
    preConfigPanelLayout.setVerticalGroup(
        preConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(preConfigPanelLayout.createSequentialGroup()
            .addComponent(titleLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(15, 15, 15))
    );

    onlineConfigPanel.setMinimumSize(new java.awt.Dimension(720, 350));
    onlineConfigPanel.setName("onlineConfigPanel"); // NOI18N

    okConfigButton1.setText(resourceMap.getString("okConfigButton1.text")); // NOI18N
    okConfigButton1.setName("okConfigButton1"); // NOI18N
    okConfigButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            okConfigButton1ActionPerformed(evt);
        }
    });

    bookingDetailsPanel1.setEnabled(false);
    bookingDetailsPanel1.setName("bookingDetailsPanel1"); // NOI18N

    entrySlotIdLabel1.setText(resourceMap.getString("entrySlotIdLabel1.text")); // NOI18N
    entrySlotIdLabel1.setName("entrySlotIdLabel1"); // NOI18N

    entrySlotsLabel1.setText(resourceMap.getString("entrySlotsLabel1.text")); // NOI18N
    entrySlotsLabel1.setName("entrySlotsLabel1"); // NOI18N

    entrySlotsSpinner1.setName("entrySlotsSpinner1"); // NOI18N
    entrySlotsSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            entrySlotsSpinner1StateChanged(evt);
        }
    });

    entrySlotIdInput3.setText(idInputDefault);
    entrySlotIdInput3.setEnabled(false);
    entrySlotIdInput3.setName("entrySlotIdInput3"); // NOI18N
    entrySlotIdInput3.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            entrySlotIdInput3inputFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            entrySlotIdInput3inputFocusLost(evt);
        }
    });

    entrySlotIdInput2.setText(idInputDefault);
    entrySlotIdInput2.setEnabled(false);
    entrySlotIdInput2.setName("entrySlotIdInput2"); // NOI18N
    entrySlotIdInput2.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            entrySlotIdInput2inputFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            entrySlotIdInput2inputFocusLost(evt);
        }
    });

    entrySlotIdLabel3.setText(resourceMap.getString("entrySlotIdLabel3.text")); // NOI18N
    entrySlotIdLabel3.setName("entrySlotIdLabel3"); // NOI18N

    entrySlotIdLabel2.setText(resourceMap.getString("entrySlotIdLabel2.text")); // NOI18N
    entrySlotIdLabel2.setName("entrySlotIdLabel2"); // NOI18N

    waitingListButtonGroup.add(noLoadWaitingListRadioButton);
    noLoadWaitingListRadioButton.setText(resourceMap.getString("noLoadWaitingListRadioButton.text")); // NOI18N
    noLoadWaitingListRadioButton.setName("noLoadWaitingListRadioButton"); // NOI18N
    noLoadWaitingListRadioButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            noLoadWaitingListRadioButtonActionPerformed(evt);
        }
    });

    loadWaitingListLabel.setText(resourceMap.getString("loadWaitingListLabel.text")); // NOI18N
    loadWaitingListLabel.setName("loadWaitingListLabel"); // NOI18N

    entrySlotIdInput1.setText(idInputDefault);
    entrySlotIdInput1.setName("entrySlotIdInput1"); // NOI18N
    entrySlotIdInput1.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            entrySlotIdInput1inputFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            entrySlotIdInput1inputFocusLost(evt);
        }
    });

    waitingListButtonGroup.add(yesLoadWaitingListRadioButton);
    yesLoadWaitingListRadioButton.setSelected(true);
    yesLoadWaitingListRadioButton.setText(resourceMap.getString("yesLoadWaitingListRadioButton.text")); // NOI18N
    yesLoadWaitingListRadioButton.setName("yesLoadWaitingListRadioButton"); // NOI18N
    yesLoadWaitingListRadioButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            yesLoadWaitingListRadioButtonActionPerformed(evt);
        }
    });

    generatedTitle1.setText(resourceMap.getString("generatedTitle1.text")); // NOI18N
    generatedTitle1.setEnabled(false);
    generatedTitle1.setName("generatedTitle1"); // NOI18N

    generatedTitle2.setText(resourceMap.getString("generatedTitle2.text")); // NOI18N
    generatedTitle2.setEnabled(false);
    generatedTitle2.setName("generatedTitle2"); // NOI18N

    generatedTitle3.setText(resourceMap.getString("generatedTitle3.text")); // NOI18N
    generatedTitle3.setEnabled(false);
    generatedTitle3.setName("generatedTitle3"); // NOI18N

    loadEventButton1.setText(resourceMap.getString("loadEventButton1.text")); // NOI18N
    loadEventButton1.setName("loadEventButton1"); // NOI18N
    loadEventButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            loadEventButtonActionPerformed(evt);
        }
    });

    loadEventButton2.setText(resourceMap.getString("loadEventButton2.text")); // NOI18N
    loadEventButton2.setEnabled(false);
    loadEventButton2.setName("loadEventButton2"); // NOI18N
    loadEventButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            loadEventButtonActionPerformed(evt);
        }
    });

    loadEventButton3.setText(resourceMap.getString("loadEventButton3.text")); // NOI18N
    loadEventButton3.setEnabled(false);
    loadEventButton3.setName("loadEventButton3"); // NOI18N
    loadEventButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            loadEventButtonActionPerformed(evt);
        }
    });

    generatedTitleLabel1.setText(resourceMap.getString("generatedTitleLabel1.text")); // NOI18N
    generatedTitleLabel1.setName("generatedTitleLabel1"); // NOI18N

    generatedTitleLabel2.setText(resourceMap.getString("generatedTitleLabel2.text")); // NOI18N
    generatedTitleLabel2.setName("generatedTitleLabel2"); // NOI18N

    generatedTitleLabel3.setText(resourceMap.getString("generatedTitleLabel3.text")); // NOI18N
    generatedTitleLabel3.setName("generatedTitleLabel3"); // NOI18N

    aboutEventLabel.setFont(resourceMap.getFont("aboutEventLabel.font")); // NOI18N
    aboutEventLabel.setText(resourceMap.getString("aboutEventLabel.text")); // NOI18N
    aboutEventLabel.setName("aboutEventLabel"); // NOI18N

    javax.swing.GroupLayout bookingDetailsPanel1Layout = new javax.swing.GroupLayout(bookingDetailsPanel1);
    bookingDetailsPanel1.setLayout(bookingDetailsPanel1Layout);
    bookingDetailsPanel1Layout.setHorizontalGroup(
        bookingDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(bookingDetailsPanel1Layout.createSequentialGroup()
            .addGroup(bookingDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bookingDetailsPanel1Layout.createSequentialGroup()
                    .addComponent(entrySlotsLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(entrySlotsSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(24, 24, 24)
                    .addGroup(bookingDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bookingDetailsPanel1Layout.createSequentialGroup()
                            .addComponent(entrySlotIdLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(entrySlotIdInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(loadEventButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                        .addGroup(bookingDetailsPanel1Layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(loadWaitingListLabel)
                            .addGap(4, 4, 4)
                            .addComponent(yesLoadWaitingListRadioButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(noLoadWaitingListRadioButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingDetailsPanel1Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(generatedTitleLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(generatedTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingDetailsPanel1Layout.createSequentialGroup()
                    .addGap(306, 306, 306)
                    .addGroup(bookingDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(generatedTitleLabel3)
                        .addComponent(entrySlotIdLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(bookingDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(generatedTitle3, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                        .addGroup(bookingDetailsPanel1Layout.createSequentialGroup()
                            .addComponent(entrySlotIdInput3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(loadEventButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingDetailsPanel1Layout.createSequentialGroup()
                    .addGap(306, 306, 306)
                    .addGroup(bookingDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(generatedTitleLabel2)
                        .addComponent(entrySlotIdLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(bookingDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bookingDetailsPanel1Layout.createSequentialGroup()
                            .addComponent(entrySlotIdInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(loadEventButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                        .addComponent(generatedTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)))
                .addComponent(aboutEventLabel))
            .addContainerGap())
    );
    bookingDetailsPanel1Layout.setVerticalGroup(
        bookingDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(bookingDetailsPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(aboutEventLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(bookingDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(entrySlotsLabel1)
                .addComponent(entrySlotsSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(entrySlotIdLabel1)
                .addComponent(entrySlotIdInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(loadEventButton1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(bookingDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(generatedTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(generatedTitleLabel1))
            .addGap(33, 33, 33)
            .addGroup(bookingDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(entrySlotIdLabel2)
                .addComponent(entrySlotIdInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(loadEventButton2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(bookingDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(generatedTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(generatedTitleLabel2))
            .addGap(37, 37, 37)
            .addGroup(bookingDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(entrySlotIdInput3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(entrySlotIdLabel3)
                .addComponent(loadEventButton3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(bookingDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(generatedTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(generatedTitleLabel3))
            .addGap(18, 18, 18)
            .addGroup(bookingDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(loadWaitingListLabel)
                .addComponent(yesLoadWaitingListRadioButton)
                .addComponent(noLoadWaitingListRadioButton))
            .addContainerGap(16, Short.MAX_VALUE))
    );

    clearButton2.setText(resourceMap.getString("clearButton2.text")); // NOI18N
    clearButton2.setName("clearButton2"); // NOI18N
    clearButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            clearButton2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout onlineConfigPanelLayout = new javax.swing.GroupLayout(onlineConfigPanel);
    onlineConfigPanel.setLayout(onlineConfigPanelLayout);
    onlineConfigPanelLayout.setHorizontalGroup(
        onlineConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(onlineConfigPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(onlineConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, onlineConfigPanelLayout.createSequentialGroup()
                    .addComponent(okConfigButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 494, Short.MAX_VALUE)
                    .addComponent(clearButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23))
                .addGroup(onlineConfigPanelLayout.createSequentialGroup()
                    .addComponent(bookingDetailsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())))
    );
    onlineConfigPanelLayout.setVerticalGroup(
        onlineConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, onlineConfigPanelLayout.createSequentialGroup()
            .addComponent(bookingDetailsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(onlineConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(clearButton2)
                .addComponent(okConfigButton1))
            .addContainerGap())
    );

    setComponent(preConfigPanel);
    setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    @Action
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        switchToPanel(configPanel);
    }//GEN-LAST:event_backButtonActionPerformed

    @Action
    private void enterStudentNumberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterStudentNumberButtonActionPerformed
        checkBooking();
    }//GEN-LAST:event_enterStudentNumberButtonActionPerformed
    
    @Action
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        EventSwipeApp.getApplication().saveAttendeesToFile();
    }//GEN-LAST:event_saveButtonActionPerformed

    @Action
    private void checkingModeToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingModeToggleActionPerformed
        toggleCheckingMode();
    }//GEN-LAST:event_checkingModeToggleActionPerformed

    @Action
    private void clearButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton1ActionPerformed
        clearSession(evt);
    }//GEN-LAST:event_clearButton1ActionPerformed

    @Action
    private void toggleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleMenuItemActionPerformed
        checkingModeToggle.doClick();
    }//GEN-LAST:event_toggleMenuItemActionPerformed

    private void okConfigButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okConfigButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okConfigButton1ActionPerformed

    private void entrySlotsSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_entrySlotsSpinner1StateChanged
        updateOnlineBookingPanel(true);
    }//GEN-LAST:event_entrySlotsSpinner1StateChanged

    private void entrySlotIdInput3inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entrySlotIdInput3inputFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entrySlotIdInput3inputFocusGained

    private void entrySlotIdInput3inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entrySlotIdInput3inputFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_entrySlotIdInput3inputFocusLost

    private void entrySlotIdInput2inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entrySlotIdInput2inputFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entrySlotIdInput2inputFocusGained

    private void entrySlotIdInput2inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entrySlotIdInput2inputFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_entrySlotIdInput2inputFocusLost

    private void noLoadWaitingListRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noLoadWaitingListRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noLoadWaitingListRadioButtonActionPerformed

    private void entrySlotIdInput1inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entrySlotIdInput1inputFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entrySlotIdInput1inputFocusGained

    private void entrySlotIdInput1inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entrySlotIdInput1inputFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_entrySlotIdInput1inputFocusLost

    private void yesLoadWaitingListRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesLoadWaitingListRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesLoadWaitingListRadioButtonActionPerformed

    private void clearButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearButton2ActionPerformed

@Action()
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearSession(evt);
}//GEN-LAST:event_clearButtonActionPerformed

@Action()
private void inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputFocusLost
    JFormattedTextField input = (JFormattedTextField) evt.getSource();
    if (input == eventTitleInput && input.getText().equals(""))
        input.setText(titleInputDefault);
    else if (input.getText().equals(""))
        input.setText(fileInputDefault);
}//GEN-LAST:event_inputFocusLost

@Action()
private void inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputFocusGained
    JFormattedTextField input = (JFormattedTextField) evt.getSource();
    if (input == eventTitleInput && input.getText().equals(titleInputDefault))
        input.setText("");
    else if (input.getText().equals(fileInputDefault))
        input.setText("");
}//GEN-LAST:event_inputFocusGained

@Action()
private void yesWaitingListRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesWaitingListRadioButtonActionPerformed
    updateBookingPanel(true);
}//GEN-LAST:event_yesWaitingListRadioButtonActionPerformed

@Action()
private void noWaitingListRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noWaitingListRadioButtonActionPerformed
    updateBookingPanel(true);
}//GEN-LAST:event_noWaitingListRadioButtonActionPerformed

@Action()
private void browseFileAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFileAction
    JFileChooser fc = new JFileChooser();
    File file = null;
    fc.addChoosableFileFilter(new TextCSVFilter());
    int returnVal = fc.showDialog(EventSwipeApp.getApplication().getMainFrame(), "Choose");
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        file = fc.getSelectedFile();
        if (evt.getSource() == bookingListBrowseButton1) {
            entrySlotBookingListFilePathInput1.setText(file.getPath());
        }
        if (evt.getSource() == bookingListBrowseButton2) {
            entrySlotBookingListFilePathInput2.setText(file.getPath());
        }
        if (evt.getSource() == bookingListBrowseButton3) {
            entrySlotBookingListFilePathInput3.setText(file.getPath());
        }
        if (evt.getSource() == waitingListBrowseButton) {
            waitingListFilePathInput.setText(file.getPath());
        }
    }
}//GEN-LAST:event_browseFileAction

@Action()
private void entrySlotsSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_entrySlotsSpinnerStateChanged
    updateBookingPanel(true);
}//GEN-LAST:event_entrySlotsSpinnerStateChanged

@Action()
private void okConfigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okConfigButtonActionPerformed
    checkConfiguration();
}//GEN-LAST:event_okConfigButtonActionPerformed

@Action()
private void noBookingRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBookingRadioButtonActionPerformed
    updateBookingPanel(yesBookingRadioButton.isSelected());
}//GEN-LAST:event_noBookingRadioButtonActionPerformed

@Action()
private void yesBookingRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBookingRadioButtonActionPerformed
    updateBookingPanel(yesBookingRadioButton.isSelected());
}//GEN-LAST:event_yesBookingRadioButtonActionPerformed

@Action()
private void loadEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadEventButtonActionPerformed
        if (evt.getSource() == loadEventButton1) {
            String id = entrySlotIdInput1.getText();
            if (id.isEmpty()) {
                JOptionPane.showMessageDialog(EventSwipeApp.getApplication().getMainFrame(),
                                              "You have not entered an entry slot ID!",
                                              "Event ID error",
                                              JOptionPane.ERROR_MESSAGE);
            }
            else {
                String slotTitle = "";
                try {
                    slotTitle = EventSwipeApp.getApplication().getSlotTitle(id);
                } catch (IOException ex) {
                    Logger.getLogger(EventSwipeView.class.getName()).log(Level.SEVERE, null, ex);
                }
                generatedTitle1.setText(slotTitle);
            }
        }
        if (evt.getSource() == loadEventButton2) {
            String id = entrySlotIdInput2.getText();
            if (id.isEmpty()) {
                JOptionPane.showMessageDialog(EventSwipeApp.getApplication().getMainFrame(),
                                              "You have not entered an entry slot ID!",
                                              "Event ID error",
                                              JOptionPane.ERROR_MESSAGE);
            }
            else {
                String slotTitle = "";
                try {
                    slotTitle = EventSwipeApp.getApplication().getSlotTitle(id);
                } catch (IOException ex) {
                    Logger.getLogger(EventSwipeView.class.getName()).log(Level.SEVERE, null, ex);
                }
                generatedTitle2.setText(slotTitle);
            }
        }
        if (evt.getSource() == loadEventButton3) {
            String id = entrySlotIdInput3.getText();
            if (id.isEmpty()) {
                JOptionPane.showMessageDialog(EventSwipeApp.getApplication().getMainFrame(),
                                              "You have not entered an entry slot ID!",
                                              "Event ID error",
                                              JOptionPane.ERROR_MESSAGE);
            }
            else {
                String slotTitle = "";
                try {
                    slotTitle = EventSwipeApp.getApplication().getSlotTitle(id);
                } catch (IOException ex) {
                    Logger.getLogger(EventSwipeView.class.getName()).log(Level.SEVERE, null, ex);
                }
                generatedTitle3.setText(slotTitle);
            }
        }
}//GEN-LAST:event_loadEventButtonActionPerformed
    
    private void checkConfiguration() {
        EventSwipeApp.getApplication().setBookingFlag(yesBookingRadioButton.isSelected());
        EventSwipeApp.getApplication().setWaitingListFlag(yesWaitingListRadioButton.isSelected());
        EventSwipeApp.getApplication().setSlots((Integer)entrySlotsSpinner.getValue());
        boolean configOK = false;
        if (eventTitleInput.getText().equals(titleInputDefault)) {
            JOptionPane.showMessageDialog(EventSwipeApp.getApplication().getMainFrame(),
                                          "You have not entered an event title. Please write one!",
                                          "Event title error",
                                          JOptionPane.ERROR_MESSAGE);
        }
        else {
            EventSwipeApp.getApplication().setEventTitle(eventTitleInput.getText());
            configOK = true;
        }
        if (configOK && EventSwipeApp.getApplication().getBookingFlag() && EventSwipeApp.getApplication().getSlots() > 0)
            configOK = EventSwipeApp.getApplication().setFile(BookingList.BOOKING_1, new File(entrySlotBookingListFilePathInput1.getText()));
        if (configOK && EventSwipeApp.getApplication().getBookingFlag() && EventSwipeApp.getApplication().getSlots() > 1)
            configOK = EventSwipeApp.getApplication().setFile(BookingList.BOOKING_2, new File(entrySlotBookingListFilePathInput2.getText()));
        if (configOK && EventSwipeApp.getApplication().getBookingFlag() && EventSwipeApp.getApplication().getSlots() > 2)
            configOK = EventSwipeApp.getApplication().setFile(BookingList.BOOKING_3, new File(entrySlotBookingListFilePathInput3.getText()));
        if (configOK && EventSwipeApp.getApplication().getBookingFlag() && EventSwipeApp.getApplication().getWaitingListFlag())
            configOK = EventSwipeApp.getApplication().setFile(BookingList.WAITING_LIST, new File(waitingListFilePathInput.getText()));
        if (configOK) {
            EventSwipeApp.getApplication().createLog(eventTitleInput.getText());
            switchToPanel(mainPanel);
        }
    }

    private void checkBooking() {
        String stuNumber = studentNumberInput.getText();
        if (stuNumber.isEmpty()) {
            JOptionPane.showMessageDialog(EventSwipeApp.getApplication().getMainFrame(),
                                          "Please enter a student number!",
                                          "No student number",
                                          JOptionPane.ERROR_MESSAGE);
        }
        else {
            updateBookingStatus(EventSwipeApp.getApplication().checkBooking(stuNumber));
        }
    }

    private void updateBookingStatus(Booking booking) {
        String stuNumber = booking.getStuNumber();
        String message = "Student " + stuNumber;
        String slot = booking.getEntrySlot() == 0 ? "N/A" : booking.getEntrySlot().toString();
        slot = booking.isOnWaitingList() ? "W/L" : slot;
        String bookingStatus = "";
        if (booking.isAlreadyRecorded()) {
            message += " has already been recorded";
            bookingStatus = "Already recorded";
        }
        else if(booking.isOnWaitingList()) {
            Utils.pressAlt();
            int reply = JOptionPane.showConfirmDialog(EventSwipeApp.getApplication().getMainFrame(),
                                                      "Student is on the waiting list. "
                                                      + "Allow student to enter?",
                                                      "Student on waiting list",
                                                      JOptionPane.YES_NO_OPTION);
            Utils.releaseAlt();
            if (reply == JOptionPane.YES_OPTION) {
                EventSwipeApp.getApplication().recordAttendance(stuNumber, 0);
                bookingStatus = "Recorded";
                message += " has been recorded";
            }
            else {
                bookingStatus = "Waiting list";
                message += " is on the waiting list";
            }
        }
        else if (booking.isBooked()) {
            if (EventSwipeApp.getApplication().getBookingFlag()) {
                bookingStatus = "Booked";
                message += " has booked";
                if (EventSwipeApp.getApplication().getSlots() > 1) {
                    message += " for entry slot " + slot;
                }
            }
            else {
                bookingStatus = "Recorded";
                message += " has been recorded";
            }
        }
        else { //not booked
            Utils.pressAlt();
            int reply = JOptionPane.showConfirmDialog(EventSwipeApp.getApplication().getMainFrame(),
                                                      "Student is not booked. "
                                                      + "Allow student to enter?",
                                                      "Student not booked",
                                                      JOptionPane.YES_NO_OPTION);
            Utils.releaseAlt();
            if (reply == JOptionPane.YES_OPTION) {
                EventSwipeApp.getApplication().recordAttendance(stuNumber, 0);
                bookingStatus = "Recorded";
                message += " has been recorded";
            }
            else {
                message += " has NOT booked onto this event";
                bookingStatus = "Not booked";
            }
        }
        displayBookingStatus(bookingStatus, slot);
        displayBookingMessage(message);
        EventSwipeApp.getApplication().log(message);
    }

    private void displayBookingMessage(String message) {
        message += "\n";
        bookingStatusTextArea.append(message);
        studentNumberInput.setText("");
        studentNumberInput.requestFocusInWindow();
    }

    private void displayBookingStatus(String statusMessage, String slot) {
        statusDisplayTextField.setText(statusMessage);
        entrySlotDisplayTextField.setText(slot);
        Color color;
        boolean enabled;
        if(statusMessage.equals("Booked")) {
            color = Color.GREEN;
            enabled = true;
            attendeeCountDisplayTextField.setText(EventSwipeApp.getApplication()
                                                  .getAttendeeCount());
        }
        else if(statusMessage.equals("Recorded") || statusMessage.equals("")) {
            color = Color.WHITE;
            enabled = false;
            attendeeCountDisplayTextField.setText(EventSwipeApp.getApplication()
                                                  .getAttendeeCount());
        }
        else {
            enabled = false;
            color = statusMessage.equals("Not booked") ? Color.RED : Color.ORANGE;
        }
        statusDisplayTextField.setBackground(color);
        entrySlotLabel.setEnabled(enabled);
        entrySlotDisplayTextField.setEnabled(enabled);
        //set up and start timer to remove background colour from bookking status
        int delay = 250; //milliseconds
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                statusDisplayTextField.setBackground(null);
            }
        };
        Timer timer = new Timer(delay, taskPerformer);
        timer.setRepeats(false);
        timer.start();
    }

    private void switchToPanel(JPanel panel) {
        JFrame mainFrame = EventSwipeApp.getApplication().getMainFrame();
        mainFrame.setContentPane(panel);
        if (panel == mainPanel)
            studentNumberInput.requestFocusInWindow();
        panel.revalidate();
        mainFrame.repaint();
    }

    private void updateBookingPanel(boolean enabled) {
        Integer slots = (Integer)entrySlotsSpinner.getValue();
        bookingDetailsPanel.setEnabled(enabled);
        bookingListBrowseButton1.setEnabled(enabled);
        bookingListBrowseButton2.setEnabled(enabled && slots > 1);
        bookingListBrowseButton3.setEnabled(enabled && slots > 2);
        waitingListBrowseButton.setEnabled(enabled &&
                                           yesWaitingListRadioButton.isSelected());
        entrySlotBookingListFilePathInput1.setEnabled(enabled);
        entrySlotBookingListFilePathInput2.setEnabled(enabled && slots > 1);
        entrySlotBookingListFilePathInput3.setEnabled(enabled && slots > 2);
        waitingListFilePathInput.setEnabled(enabled &&
                                            yesWaitingListRadioButton.isSelected());
        entrySlotBookingListLabel1.setEnabled(enabled);
        entrySlotBookingListLabel2.setEnabled(enabled && slots > 1);
        entrySlotBookingListLabel3.setEnabled(enabled && slots > 2);
        waitingListFileLabel.setEnabled(enabled &&
                             yesWaitingListRadioButton.isSelected());
        entrySlotsLabel.setEnabled(enabled);
        entrySlotsSpinner.setEnabled(enabled);
        noWaitingListRadioButton.setEnabled(enabled);
        yesWaitingListRadioButton.setEnabled(enabled);
        waitingListLabel.setEnabled(enabled);
        entrySlotLabel.setEnabled(enabled);
        entrySlotDisplayTextField.setText(enabled ? "": "N/A");
        entrySlotDisplayTextField.setEnabled(enabled);
        checkingModeToggle.setEnabled(enabled);
        checkingModeToggle.setText(enabled ? "Checking booking lists" :
                                             "Recording all students");
        checkingModeToggle.setSelected(enabled);
        toggleMenuItem.setEnabled(enabled);
    }

    private void updateOnlineBookingPanel(boolean enabled) {
        Integer slots = (Integer)entrySlotsSpinner1.getValue();
        bookingDetailsPanel.setEnabled(enabled);

        loadEventButton1.setEnabled(enabled);
        entrySlotIdInput1.setEnabled(enabled);

        loadEventButton2.setEnabled(enabled && slots > 1);
        entrySlotIdInput2.setEnabled(enabled && slots > 1);

        loadEventButton3.setEnabled(enabled && slots > 2);
        entrySlotIdInput3.setEnabled(enabled && slots > 2);

        checkingModeToggle.setEnabled(enabled);
        checkingModeToggle.setText(enabled ? "Checking booking lists" :
                                             "Recording all students");
        checkingModeToggle.setSelected(enabled);
        toggleMenuItem.setEnabled(enabled);
    }


    private void toggleCheckingMode() {
        if (checkingModeToggle.isSelected()) {
            EventSwipeApp.getApplication().setBookingFlag(true);
            checkingModeToggle.setText("Checking booking lists");
        }
        else {
            EventSwipeApp.getApplication().setBookingFlag(false);
            checkingModeToggle.setText("Recording all students");
        }
    }

    private void clearSession(java.awt.event.ActionEvent evt) {
        Utils.pressAlt();
        int reply = JOptionPane.showConfirmDialog(EventSwipeApp.getApplication().getMainFrame(),
                                                      "Clear all booking data and restart session?",
                                                      "Clear all data warning",
                                                      JOptionPane.YES_NO_OPTION);
        Utils.releaseAlt();
        if (reply == JOptionPane.YES_OPTION) {
            if (evt.getSource().equals(clearButton1))
                switchToPanel(configPanel);
            EventSwipeApp.getApplication().clearData();
            eventTitleInput.setText(titleInputDefault);
            entrySlotBookingListFilePathInput1.setText(fileInputDefault);
            entrySlotBookingListFilePathInput2.setText(fileInputDefault);
            entrySlotBookingListFilePathInput3.setText(fileInputDefault);
            waitingListFilePathInput.setText(fileInputDefault);
            entrySlotsSpinner.setValue(1);
            noWaitingListRadioButton.setSelected(true);
            noBookingRadioButton.setSelected(true);
            displayBookingStatus("", "N/A");
            bookingStatusTextArea.setText("");
            eventTitleInput.requestFocusInWindow();
            updateBookingPanel(false);
        }
    }

    @Action
    public void logIn() {
        String username = usernameInput.getText();
        char[] password = passwordInput.getPassword();
        if (username.isEmpty() || username.equals(usernameInputDefault)) {
            JOptionPane.showMessageDialog(EventSwipeApp.getApplication().getMainFrame(),
                                          "Please enter your CareerHub username.",
                                          "No username",
                                          JOptionPane.ERROR_MESSAGE);
        }
        else if (password.length == 0) {
            JOptionPane.showMessageDialog(EventSwipeApp.getApplication().getMainFrame(),
                                          "Please enter your CareerHub password.",
                                          "No password",
                                          JOptionPane.ERROR_MESSAGE);
        }
        else {
            try {
                EventSwipeApp.getApplication().logIn(username, password);
                switchToPanel(onlineConfigPanel);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(EventSwipeApp.getApplication().getMainFrame(),
                                              "Your username or password were incorrect." +
                                              "Please try again",
                                              "Log in error",
                                              JOptionPane.ERROR_MESSAGE);
            }
        }
        Arrays.fill(password,'0');
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutEventLabel;
    private javax.swing.JFormattedTextField attendeeCountDisplayTextField;
    private javax.swing.JLabel attendeeCountLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel bookingDetailsPanel;
    private javax.swing.JPanel bookingDetailsPanel1;
    private javax.swing.JButton bookingListBrowseButton1;
    private javax.swing.JButton bookingListBrowseButton2;
    private javax.swing.JButton bookingListBrowseButton3;
    private javax.swing.JScrollPane bookingStatusScrollPane;
    private javax.swing.JTextArea bookingStatusTextArea;
    private javax.swing.JToggleButton checkingModeToggle;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton clearButton1;
    private javax.swing.JButton clearButton2;
    private javax.swing.JPanel configPanel;
    private javax.swing.JButton enterStudentNumberButton;
    private javax.swing.JFormattedTextField entrySlotBookingListFilePathInput1;
    private javax.swing.JFormattedTextField entrySlotBookingListFilePathInput2;
    private javax.swing.JFormattedTextField entrySlotBookingListFilePathInput3;
    private javax.swing.JLabel entrySlotBookingListLabel1;
    private javax.swing.JLabel entrySlotBookingListLabel2;
    private javax.swing.JLabel entrySlotBookingListLabel3;
    private javax.swing.JFormattedTextField entrySlotDisplayTextField;
    private javax.swing.JFormattedTextField entrySlotIdInput1;
    private javax.swing.JFormattedTextField entrySlotIdInput2;
    private javax.swing.JFormattedTextField entrySlotIdInput3;
    private javax.swing.JLabel entrySlotIdLabel1;
    private javax.swing.JLabel entrySlotIdLabel2;
    private javax.swing.JLabel entrySlotIdLabel3;
    private javax.swing.JLabel entrySlotLabel;
    private javax.swing.JLabel entrySlotsLabel;
    private javax.swing.JLabel entrySlotsLabel1;
    private javax.swing.JSpinner entrySlotsSpinner;
    private javax.swing.JSpinner entrySlotsSpinner1;
    private javax.swing.JFormattedTextField eventTitleInput;
    private javax.swing.JLabel eventTitleInputLabel;
    private javax.swing.JTextField generatedTitle1;
    private javax.swing.JTextField generatedTitle2;
    private javax.swing.JTextField generatedTitle3;
    private javax.swing.JLabel generatedTitleLabel1;
    private javax.swing.JLabel generatedTitleLabel2;
    private javax.swing.JLabel generatedTitleLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadEventButton1;
    private javax.swing.JButton loadEventButton2;
    private javax.swing.JButton loadEventButton3;
    private javax.swing.JLabel loadWaitingListLabel;
    private javax.swing.JButton logInButton;
    private javax.swing.JLabel logInLabel;
    private javax.swing.JSeparator loginOfflineSeparator;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JRadioButton noBookingRadioButton;
    private javax.swing.JRadioButton noLoadWaitingListRadioButton;
    private javax.swing.JRadioButton noWaitingListRadioButton;
    private javax.swing.JButton okConfigButton;
    private javax.swing.JButton okConfigButton1;
    private javax.swing.JPanel onlineConfigPanel;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel preConfigPanel;
    private javax.swing.ButtonGroup requireBookingButtonGroup;
    private javax.swing.JLabel requireBookingLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JLabel smallLogoLabel;
    private javax.swing.JButton startOfflineButton;
    private javax.swing.JFormattedTextField statusDisplayTextField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JFormattedTextField studentNumberInput;
    private javax.swing.JLabel studentNumberInputLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titleLoginPanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JMenuItem toggleMenuItem;
    private javax.swing.JTextArea useOfflineDescription;
    private javax.swing.JLabel useOfflineLabel;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JButton waitingListBrowseButton;
    private javax.swing.ButtonGroup waitingListButtonGroup;
    private javax.swing.JLabel waitingListFileLabel;
    private javax.swing.JFormattedTextField waitingListFilePathInput;
    private javax.swing.JLabel waitingListLabel;
    private javax.swing.JRadioButton yesBookingRadioButton;
    private javax.swing.JRadioButton yesLoadWaitingListRadioButton;
    private javax.swing.JRadioButton yesWaitingListRadioButton;
    // End of variables declaration//GEN-END:variables
    private JDialog aboutBox;
    private String titleInputDefault;
    private String fileInputDefault;
    private String idInputDefault;
    private String usernameInputDefault;

}
